- name: install nvidia-docker gpg
  become: yes
  shell: |
    curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | apt-key add -
    distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
    curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | tee /etc/apt/sources.list.d/nvidia-docker.list
    apt update

- name: add graphics drivers repo
  become: yes
  apt_repository:
    repo: ppa:graphics-drivers/ppa

- name: install packages for graphics
  become: yes
  apt:
    name: ["ubuntu-drivers-common","nvidia-driver-495","nvidia-container-toolkit"]
    state: present
    
- name: remove desktop
  become: yes
  apt:
    name: ubuntu-desktop
    state: absent