- name: check longhorn dependences
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - bash
    - curl
    - grep
    - mawk
    - util-linux
    - open-iscsi

- name: start iscsid
  become: yes
  command: systemctl start iscsid