- name: make sure longhorn dependences are installed
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - bash
    - curl
    - grep
    - mawk
    - util-linux
    - open-iscsi

- name: make sure iscsid is started
  become: yes
  command: systemctl start iscsid