- name: install resolveconf
  become: yes
  apt:
    name: resolvconf
    state: present

- name: start and enable resolvconf
  become: yes
  service:
    name: resolvconf
    state: started
    enabled: yes

- name: add self/router for upstream dns (this forwards to the kubernetes cluster)
  become: yes
  blockinfile:
    path: /etc/resolvconf/resolv.conf.d/head
    block: |
      nameserver 10.0.2.1

- name: update resolveconf
  become: yes
  command: resolvconf -u

- name: stop and disable systemd
  become: yes
  service:
    name: systemd-resolved
    state: stopped
    enabled: no