- name: 'Provision Image'  
  hosts: default 
  become: true
  vars_files:
    - ./vars.yml

  tasks:    
    - name: apt update machines      
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: true

    - name: install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - linux-generic
        - linux-headers-generic
        - linux-image-generic
        - qemu-guest-agent
        - cloud-utils
        - cloud-init
        - iputils-ping
        - curl
        - wget
        - nfs-common

    - name: Add public SSH key for the packer user
      authorized_key:
        user: packer
        key: "{{ item }}"
        state: present
      loop: "{{ query('hashi_vault', 'secret=kv/data/ssh-pub-key', token=vault_token, url=vault_addr, return_format='values') }}"
      register: add_identity_key
      when: vault_token is defined and vault_addr is defined

    - name: Disable empty password login
      lineinfile:
        path: "{{ sshd_config }}" 
        regexp: '^#?PermitEmptyPasswords' 
        line: 'PermitEmptyPasswords no'
      notify: restart sshd

    - name: Disable remote root login
      lineinfile: 
        path: "{{ sshd_config }}" 
        regexp: '^#?PermitRootLogin' 
        line: 'PermitRootLogin no'
      notify: restart sshd

    - name: Disable password login
      lineinfile: 
        path: "{{ sshd_config }}" 
        regexp: '^(#\s*)?PasswordAuthentication '
        line: 'PasswordAuthentication no'
      when: 
        - add_identity_key is succeeded 
        - not add_identity_key is skipped
      notify: restart sshd

  handlers:
    - name: restart sshd
      service: name={{ sshd }} state=restarted