- name: configure tc to alter datagram
  become: yes
  shell: |
    tc qdisc add dev eth0 root handle 10: htb
    tc filter add dev eth0 parent 10: protocol ip prio 10 u32 match ip src {{ansible_eth0.ipv4.address}} match ip sport 53 0xffff action nat egress {{ansible_eth0.ipv4.address}} {{loadbalancer_ip}}
