all:
  children:
    prod:
      children:
        hosts:
          jellyfin:
          website:
          webservices:
          gitlab:
          database:
    proxmox:
      hosts:
        pve1:
          ansible_host: pve.alteredtech.home
          ansible_user: "{{ lookup('hashi_vault', 'secret=kv/data/prox-access:username', token=vault_token, url=vault_addr) }}"
          ansible_ssh_pass: "{{ lookup('hashi_vault', 'secret=kv/data/prox-access:password', token=vault_token, url=vault_addr) }}"
          ansible_become_password: "{{ lookup('hashi_vault', 'secret=kv/data/prox-access:password', token=vault_token, url=vault_addr) }}"
    ubuntu:
      hosts:
        jellyfin:
          ansible_host: jellyfin.alteredtech.home
          ansible_user: jellyfin
          ansible_ssh_pass: jellyfin
          ansible_become_password: jellyfin
        sandbox:
          ansible_host: 10.0.2.19
          ansible_user: packer
          ansible_ssh_pass: packer
          ansible_become_password: packer
    centos:
      hosts:
        website:
          ansible_host: 10.10.1.10
          ansible_user: websiteadmin
          ansible_become_password: "{{ lookup('hashi_vault', 'secret=kv/data/uk-servers:website', token=vault_token, url=vault_addr) }}"
          ansible_ssh_pass: "{{ lookup('hashi_vault', 'secret=kv/data/uk-servers:website', token=vault_token, url=vault_addr) }}"
        webservices:
          ansible_host: 10.10.1.5
          ansible_user: webservice
          ansible_become_password: "{{ lookup('hashi_vault', 'secret=kv/data/uk-servers:webservices', token=vault_token, url=vault_addr) }}"
          ansible_ssh_pass: "{{ lookup('hashi_vault', 'secret=kv/data/uk-servers:webservices', token=vault_token, url=vault_addr) }}"
        gitlab:
          ansible_host: 10.10.1.20
          ansible_user: gitlabuser
          ansible_ssh_port: 2222
          ansible_become_password: "{{ lookup('hashi_vault', 'secret=kv/data/uk-servers:gitlab', token=vault_token, url=vault_addr) }}"
          ansible_ssh_pass: "{{ lookup('hashi_vault', 'secret=kv/data/uk-servers:gitlab', token=vault_token, url=vault_addr) }}"
    databases:
      hosts:
        database-1:
          ansible_host: database-1.alteredtech.home
          ansible_user: packer
          