all:
  hosts:
    jellyfin:
      ansible_host: 10.0.2.192
      ansible_user: jellyfin
      ansible_ssh_pass: jellyfin
      ansible_become_password: jellyfin
    sandbox:
      ansible_host: 10.0.2.197
      ansible_user: packer
      ansible_ssh_pass: packer
      ansible_become_password: packer