proxmox:
  hosts:
    pve1:
      ansible_host: pve.alteredtech.home
      ansible_user: "{{ lookup('hashi_vault', 'secret=kv/data/prox-access:username', token=vault_token, url=vault_addr) }}"
      ansible_ssh_pass: "{{ lookup('hashi_vault', 'secret=kv/data/prox-access:password', token=vault_token, url=vault_addr) }}"
      ansible_become_password: "{{ lookup('hashi_vault', 'secret=kv/data/prox-access:password', token=vault_token, url=vault_addr) }}"