- name: 'Docker install jellyfin hardware acceleration'
  hosts: jellyfin

  roles:
    - update-install
    - docker-install
    - graphics-install
    - setup-jellyfin

  tasks:
    
    - name: apt update
      become: true
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: true

    - name: reboot machine
      become: yes
      reboot:

    - name: start jellyfin
      command: docker-compose -f ${HOME}/docker/jellyfin/docker-compose.yml up -d --force-recreate
      tags:
        - recreate
