#required variables
#TODO add descriptions 
locals {
  proxmox_host           = vault("kv/data/prox-node-1", "prox-host")
  proxmox_api_user       = vault("kv/data/prox-node-1", "prox-user")
  proxmox_api_token_name = vault("kv/data/prox-node-1", "prox-token-name")
  proxmox_api_token      = vault("kv/data/prox-node-1", "prox-api-token")
  ssh_username           = vault("kv/data/prox-node-1", "username")
  ssh_password           = vault("kv/data/prox-node-1", "password")
  ssh_fullname           = "packer"
}
variable "proxmox_node" {
  type    = string
  default = "pve"
}
variable "iso" {
  type    = string
  default = "ubuntu-20.04.1-legacy-server-amd64.iso"
}
variable "iso_checksum" {
  type    = string
  default = "sha256:f11bda2f2caed8f420802b59f382c25160b114ccc665dbac9c5046e7fceaced2"
}
variable "vault_addr" {
  type    = string
  default = "${env("VAULT_ADDR")}"
}
variable "vault_token" {
  type    = string
  default = "${env("VAULT_TOKEN")}"
}

#other/optional variables
variable "template_name" {
  type    = string
  default = "tplate-ubuntu-2004-ISO-CINIT"
}

variable "template_description" {
  type    = string
  default = "Ubuntu 20.04.1 Legacy (focal) x86_64, generated by packer on {{ isotime \"2006-01-02-T15-04-05\" }}-UTC. Contains Cloud-init and QEMU-agent"
}

variable "disk_size" {
  type    = string
  default = "64G"
}

variable "datastore" {
  type    = string
  default = "local-main"
}

variable "datastore_type" {
  type    = string
  default = "directory"
}

variable "iso_location" {
  type    = string
  default = "truenas-isos:iso"
}

variable "preseed_file" {
  type    = string
  default = "preseed.cfg"
}

variable "ansible_play" {
  type    = string
  default = "packer-ubuntu-20-04"
}

variable "bridge_name" {
  type    = string
  default = "vmbr0"
}