- name: make sure docker is started
  become: yes
  command: systemctl start docker

- name: create pgadmin4
  docker_container:
    name: pgadmin4
    image: dpage/pgadmin4:6.4
    state: started
    recreate: yes
    env:
      PGADMIN_DEFAULT_EMAIL: "{{ lookup('hashi_vault', 'secret=kv/data/postgres:pg-email', token=vault_token, url=vault_addr) }}"
      PGADMIN_DEFAULT_PASSWORD: "{{ lookup('hashi_vault', 'secret=kv/data/postgres:pg-password', token=vault_token, url=vault_addr) }}"
    ports:
      - "9002:80"
    healthcheck:
      test: ["CMD","curl","--fails","127.0.0.1:80"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s

- name: create postgres
  docker_container:
    name: postgres
    image: postgres:14.1-alpine
    state: started
    recreate: yes
    env:
      POSTGRES_PASSWORD: "{{ lookup('hashi_vault', 'secret=kv/data/postgres:password', token=vault_token, url=vault_addr) }}"
      POSTGRES_USER: "{{ lookup('hashi_vault', 'secret=kv/data/postgres:username', token=vault_token, url=vault_addr) }}"
      POSTGRES_DB: "k3s"
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - '/home/packer/database/postgresql/data:/var/lib/postgresql/data'
      # - '/home/packer/backups/postgresql:/bitnami/postgresql'
    ports:
      - "5432:5432"