---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: k3s-prereq }
    - { role: k3s-download }
    - { role: k3s-raspberrypi }

- hosts: master
  become: yes
  roles:
    - { role: k3s/master }

- hosts: node
  become: yes
  roles:
    - { role: k3s/node }

- hosts: "{{ groups['master'][0] | default(groups['master'][0]) }}"
  tags:
    - config
  roles:
    - { role: k3s-config }