- name: install packages
  become: yes
  apt:
    name: docker.io
    state: present

- name: install docker-compose
  become: yes
  shell: |
    curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    apt update

- name: create docker group
  become: yes
  group:
    name: ["docker","video"]
    state: present
    
- name: added '{{ ansible_ssh_user }}' to group
  become: yes
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker,video
    append: yes
