version: "3.8"
services:
  vault-server:
    container_name: vault
    image: vault:latest
    volumes:
      - "./file:/vault/file"
      - "./logs:/vault/file"
      - "./config:/vault/config"
    ports:
      - "8200:8200"
    restart: on-failure:10
    cap_add:
      - IPC_LOCK
        entrypoint: vault server -config=/vault/config/vault.json
    healthcheck:
      retries: 5