- name: 'Provision Image'  
  hosts: default 
  become: true

  tasks:    
    - name: apt update machines      
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: true
    - name: install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - linux-generic
        - linux-headers-generic
        - linux-image-generic
        - qemu-guest-agent
        - cloud-init
        - iputils-ping
        - curl
        - wget
        - nfs-common
    - name: Add public SSH key for the packer user
      authorized_key:
        user: packer
        key: '{{ lookup('hashi_vault', 'secret=kv/data/ssh-pub-key token=s.FqUJTRCqoUA6rVDoMmMEuCQo url=http://10.0.2.139:8200')}}'
        state: present