- name: create backup directory
  file:
    path: ${HOME}/backups
    state: directory

- name: Mount backups for database
  become: yes
  ansible.posix.mount:
    src: "{{ mount_point }}"
    path: backups
    opts: defaults,hard
    state: mounted
    fstype: nfs