ingress:
  enabled: true
  hosts:
  # virtualHost (default value is pi.hole) will be appended to the hosts
    - pihole.alteredtech.home

serviceDhcp:
  # -- Generate a Service resource for DHCP traffic
  enabled: false

persistentVolumeClaim:
  # -- set to true to use pvc
  enabled: true
  size: "500Mi"
  storageClass: "nfs-client"

# -- default upstream DNS 1 server to use
DNS1: "10.0.2.1"
# -- default upstream DNS 2 server to use
# DNS2: "10.0.2.14"

adlists:
  # If you want to provide blocklists, add them here.
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
  - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
  - https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
  - https://v.firebog.net/hosts/Prigent-Crypto.txt
  - https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
  - https://phishing.army/download/phishing_army_blocklist_extended.txt
  - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
  - https://v.firebog.net/hosts/Shalla-mal.txt
  - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
  - https://urlhaus.abuse.ch/downloads/hostfile/
  - https://raw.githubusercontent.com/llacb47/mischosts/master/tiktok-hosts

# -- hostname of pod
hostname: "pihole-k3s"

# -- Additional annotations for pods
podAnnotations: {}
  # Example below allows Prometheus to scape on metric port (requires pihole-exporter sidecar enabled)
  # prometheus.io/port: '9617'
  # prometheus.io/scrape: 'true'

monitoring:
  # -- Preferably adding prometheus scrape annotations rather than enabling podMonitor.
  podMonitor:
    # -- set this to true to enable podMonitor
    enabled: false
  # -- Sidecar configuration
  sidecar:
    # -- set this to true to enable podMonitor as sidecar
    enabled: false
    port: 9617
    image:
      repository: ekofr/pihole-exporter
      tag: 0.0.10
      pullPolicy: IfNotPresent
    resources:
      limits:
        memory: 128Mi
      # requests:
      #  cpu: 100m
      #  memory: 128Mi

podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - 127.0.0.1
  - 10.0.2.1