# Default values for pihole.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- The number of replicas
replicaCount: 1

# -- The `spec.strategyTpye` for updates
strategyType: RollingUpdate

# -- The maximum number of Pods that can be created over the desired number of `ReplicaSet` during updating.
maxSurge: 1

# -- The maximum number of Pods that can be unavailable during updating
maxUnavailable: 1

image:
  # -- the repostory to pull the image from
  repository: "pihole/pihole"
  # -- the docker tag, if left empty it will get it from the chart's appVersion
  tag: ""
  # -- the pull policy
  pullPolicy: IfNotPresent

dnsHostPort:
  # -- set this to true to enable dnsHostPort
  enabled: true

# -- Configuration for the DHCP service on port 67
serviceDhcp:

  # -- Generate a Service resource for DHCP traffic
  enabled: false

# -- Configuration for the Ingress
ingress:
  # -- Generate a Ingress resource
  enabled: true

  # -- Specify an ingressClassName
  # ingressClassName: nginx

  # -- Annotations for the ingress
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    # virtualHost (default value is pi.hole) will be appended to the hosts
    - pihole.alteredtech.home
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #     #- virtualHost (default value is pi.hole) will be appended to the hosts
  #      - chart-example.local

# -- `spec.PersitentVolumeClaim` configuration
persistentVolumeClaim:
  # -- set to true to use pvc
  enabled: true

  # -- specify an existing `PersistentVolumeClaim` to use
  # existingClaim: ""

  accessModes:
    - ReadWriteOnce

  size: "500Mi"

  storageClass: "nfs-client"

nodeSelector:
  dns: "true"

# -- Administrator password when not using an existing secret (see below)
adminPassword: "admin"

# -- extraEnvironmentVars is a list of extra enviroment variables to set for pihole to use
extraEnvVars:
  TZ: UTC

# -- default upstream DNS 1 server to use
DNS1: "10.0.2.1"
# -- default upstream DNS 2 server to use
DNS2: "10.0.2.14"

dnsmasq:
  # -- Add upstream dns servers. All lines will be added to the pihole dnsmasq configuration
  upstreamServers: []
  # - server=/foo.bar/192.168.178.10
  # - server=/bar.foo/192.168.178.11

  # -- Add custom dns entries to override the dns resolution. All lines will be added to the pihole dnsmasq configuration.
  customDnsEntries:
  # - address=/foo.bar/192.168.178.10
  - address=/grafana.alteredtech.home/10.0.2.20
  - address=/pihole.alteredtech.home/10.0.2.20
  - address=/plex.alteredtech.home/10.0.2.15
  - address=/vault.alteredtech.home/10.0.2.139

  # -- Dnsmasq reads the /etc/hosts file to resolve ips. You can add additional entries if you like
  additionalHostsEntries: []
  # - 192.168.0.3     host4
  # - 192.168.0.4     host5

  # -- Static DHCP config
  staticDhcpEntries: []
  # staticDhcpEntries:
  # - dhcp-host=MAC_ADDRESS,IP_ADDRESS,HOSTNAME

  # -- Other options
  customSettings:
  # otherSettings:
  # - rebind-domain-ok=/plex.direct/

  # -- Here we specify custom cname entries that should point to `A` records or
  # elements in customDnsEntries array.
  # The format should be:
  #  - cname=cname.foo.bar,foo.bar
  #  - cname=cname.bar.foo,bar.foo
  #  - cname=cname record,dns record
  customCnameEntries: []
  # Here we specify custom cname entries that should point to `A` records or
  # elements in customDnsEntries array.
  # The format should be:
  #   - cname=cname.foo.bar,foo.bar
  #   - cname=cname.bar.foo,bar.foo
  #   - cname=cname record,dns record

# -- list of adlists to import during initial start of the container
adlists:
  # If you want to provide blocklists, add them here.
- 'https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts'
- 'https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt'
- 'https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt'
- 'https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt'
- 'https://v.firebog.net/hosts/Prigent-Crypto.txt'
- 'https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt'
- 'https://phishing.army/download/phishing_army_blocklist_extended.txt'
- 'https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt'
- 'https://v.firebog.net/hosts/Shalla-mal.txt'
- 'https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt'
- 'https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts'
- 'https://urlhaus.abuse.ch/downloads/hostfile/'
- 'https://raw.githubusercontent.com/llacb47/mischosts/master/tiktok-hosts'

# -- list of whitelisted domains to import during initial start of the container
# whitelist:
#   # If you want to provide whitelisted domains, add them here.
#-(\.|^)ovrc\.com$

# -- list of blacklisted domains to import during initial start of the container
# blacklist:
#   # If you want to have special domains blacklisted, add them here
#   - googleads.g.doubleclick.net

# -- list of blacklisted regex expressions to import during initial start of the container
# regex:
#   # Add regular expression blacklist items
#   # - (^|\.)facebook\.com$
#   - (\.|^)doubleclick\.net$

# -- hostname of pod
hostname: "pihole"

# -- Additional annotations for pods
podAnnotations:
  # Example below allows Prometheus to scape on metric port (requires pihole-exporter sidecar enabled)
  prometheus.io/port: '9617'
  prometheus.io/scrape: 'true'

monitoring:
  # -- Preferably adding prometheus scrape annotations rather than enabling podMonitor.
  podMonitor:
    # -- set this to true to enable podMonitor
    enabled: true
    labels:
      release: prom-monitor
  # -- Sidecar configuration
  sidecar:
    # -- set this to true to enable podMonitor as sidecar
    enabled: true
    port: 9617
    image:
      repository: ekofr/pihole-exporter
      tag: 0.0.10
      pullPolicy: IfNotPresent
    resources:
      limits:
        memory: 128Mi
      # requests:
      #  cpu: 100m
      #  memory: 128Mi

podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - 10.0.2.1
  - 10.0.2.14
  - 127.0.0.1

