- name: apt update ubuntu machines
  become: yes
  apt:
    update_cache: yes
    upgrade: 'yes'
    autoclean: yes
  register: res
  retries: 100
  delay: 10
  until: res is not failed

- name: install docker and nfs-common
  become: yes
  apt:
    name: ['docker.io','nfs-common','python3']
    state: present

- name: create docker group
  become: yes
  group:
    name: docker
    state: present

- name: added packer to group
  become: yes
  user:
    name: packer
    groups: docker, packer
    append: yes

- name: install python package manager
  become: yes
  apt:
    name: python3-pip

- name: install python sdk
  become: yes
  pip:
    name:
      - docker
      - docker-compose

- name: reset ssh connection for docker group to take affect
  meta: reset_connection